---
title: "Glossaire"
subtitle: "Les termes les plus utilisés et leurs définitions"
format: 
  html: 
    toc: false
---

[A](#a) [B](#b) [C](#c) [D](#d) [E](#e) [F](#f) [G](#g) [H](#h) [I](#i) [J](#j) [K](#k) [L](#l) [M](#m) [N](#n) [O](#o) [P](#p) [Q](#q) [R](#r) [S](#s) [T](#t) [U](#u) [V](#v) [W](#w) [X](#x) [Y](#y) [Z](#z)

# A {#a}

## Argument {#argument}

Elément d'une [fonction](#fonction), essentiel ou optionnel, qui précise ou modifie la façon dont elle est exécutée.

# B {#b}

# C {#c}

## Commande {#commande}

Code qui exécute une action et qui contient généralement une ou plusieurs [fonctions](#fonction) 

## Commentaire {#commentaire}

Texte débutant par un `#` qui ne sera pas exécuté. Commenter un script permet d'expliquer ce que fait le code. 

## Console {#console}

Fenêtre permettant de taper du code et de l'exécuter.

**Casse** : R différencie les lettres minuscules des lettres majuscules.\
**Chemin absolu** : chemin vers un fichier à partir de la racine (ex : C:/).\
**Chemin relatif** : chemin vers un fichier à partir du [répertoire de travail](#wd).\
**Classe** : type de données contenues dans une variable (le plus souvent des caractères ou des valeurs numériques).\

# D {#d}

**Data frame** : objet à deux dimensions (lignes et colonnes) dont les éléments peuvent être de différents types.

# E {#e}

## Environnement {#environnement}

L'environnement contient votre espace de travail : données importées, objets créés, [fonctions](#fonction), ...


# F {#f}

## Fonction {#fonction}
Code exécutant une action précise (par exemple calculer une moyenne). Les [arguments](#argument) d'une fonction modifient la manière dont elle est exécutée

**Facteur** : vecteur contenant une structure interne définie par des niveaux.\
**Fonction** : code qui exécute une action.

# G {#g}

# H {#h}

# I {#i}

# J {#j}

# K {#k}

# L {#l}

# M {#m}

**Matrice** : objet à deux dimensions dont les éléments sont de même type.

# N {#n}

# O {#o}

## Objet {#objet}

R est un langage orienté objet : tout élément importé, créé et manipulé et stocké dans un objet.

# P {#p}

## Package {#package}
Ensemble de fonctionnalités supplémentaires qui peuvent être chargées dans R.

# Q {#q}

# R {#r}

[**Répertoire de travail**]{#wd} : dossier qui contient tout ce qui concerne votre session actuelle.

# S {#s}

## Script {#script}

Ce format de document contenant du code peut être sauvegardé et partagé (comme un document dans un traitement de texte). Un script peut être structuré et inclure des [commentaires](#commentaire) permettant d'expliquer ce que fait le code.

**Script** : à la façon d'un document texte, permet de rédiger et de sauvegarder du code.

# T {#t}

# U {#u}

# V {#v}

**Vecteur** : objet à une dimension, dont les éléments sont de même type.

# W {#w}

# X {#x}

# Y {#y}

# Z {#z}
